### ISSUE TITLE
Command 'discord.reconnect' Not Found error

### ISSUE THREAD

**Issue by jackwillis2005** [iCrawl/discord-vscode#341]
I am running Windows 10 latest update. I have tried deleting all the Visual Studio Code folders and re-installing. Running Discord as admin and not same with Visual Studio Code. Nothing has fixed the error. 
![image](https://user-images.githubusercontent.com/12480947/62410893-2a65db00-b5e4-11e9-8343-5651a86aaf46.png)

**Comment by iCrawl** [comment]
Should be fixed in v3.8.0

**Comment by JackW6809** [comment]
(I am on a different account now) I am running version V3.8.1 and I am still getting the error. My Discord is JackW#6809 if you need to see a video of such or something other.

**Comment by jackwillis2005** [comment]
(Re-opened)

**Comment by iCrawl** [comment]
I don't see how it could happen if you are on the latest version.

![](https://i.imgur.com/CtWaO5J.gif)

**Comment by JackW6809** [comment]
![image](https://user-images.githubusercontent.com/53652452/62414053-a248fb00-b60e-11e9-9c51-0f0af5e8caac.png)

**Comment by JackW6809** [comment]
https://media.giphy.com/media/ZXBFMyXkgWIzMHHprQ/giphy.gif **

**Comment by JackW6809** [comment]
![image](https://user-images.githubusercontent.com/53652452/62414068-d6bcb700-b60e-11e9-8893-489797341704.png)

**Comment by iCrawl** [comment]
What VSCode version is that? And can you try with Insiders

**Comment by JackW6809** [comment]
I uninstalled it and installed it again (So I assume the latest) and sure, I will try it with insiders.

**Comment by JackW6809** [comment]
With the Insiders version, it connects but does not display it as my now playing.

**Comment by JackW6809** [comment]
Is there an update for such?
